services:
  frontend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    # ports:
    #   - "3000:3000"
    networks:
      - proxy_network
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL:-ws://localhost:3001}
    restart: unless-stopped

networks:
  proxy_network:
    external: true
