x-frontend-service: &frontend-base
  build:
    context: .
    dockerfile: .docker/Dockerfile
  # ports:
  #   - "3000:3000"
  env_file:
    - .env
  environment:
    - VITE_API_URL=${VITE_API_URL:-ws://localhost:3001}
  restart: unless-stopped

services:
  frontend:
    <<: *frontend-base
    profiles: ["local", "dev", "hml"]
    ports:
      - "3000:3000"

  frontend-proxy:
    <<: *frontend-base
    profiles: ["prod"]
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
